// Generated by https://quicktype.io
package portwarden

type PortWarden []PortWardenElement

type PortWardenElement struct {
	Object          Object                 `json:"object"`
	ID              string                 `json:"id"`
	OrganizationID  interface{}            `json:"organizationId"`
	FolderID        *string                `json:"folderId"`
	Type            int64                  `json:"type"`
	Name            string                 `json:"name"`
	Notes           *string                `json:"notes"`
	Favorite        bool                   `json:"favorite"`
	Login           *Login                 `json:"login,omitempty"`
	RevisionDate    string                 `json:"revisionDate"`
	SecureNote      *SecureNote            `json:"secureNote,omitempty"`
	Attachments     []Attachment           `json:"attachments"`
	PasswordHistory []PasswordHistory      `json:"passwordHistory"`
	Fields          []Field                `json:"fields"`
	Card            *Card                  `json:"card,omitempty"`
	Identity        map[string]interface{} `json:"identity,omitempty"`
}

type Attachment struct {
	ID       string `json:"id"`
	FileName string `json:"fileName"`
	Size     string `json:"size"`
	SizeName string `json:"sizeName"`
	URL      string `json:"url"`
}

type Card struct {
	CardholderName string      `json:"cardholderName"`
	Brand          string      `json:"brand"`
	Number         string      `json:"number"`
	ExpMonth       string      `json:"expMonth"`
	ExpYear        string      `json:"expYear"`
	Code           interface{} `json:"code"`
}

type Field struct {
	Name  *string `json:"name"`
	Value *string `json:"value"`
	Type  int64   `json:"type"`
}

type Login struct {
	Username             *string     `json:"username"`
	Password             *string     `json:"password"`
	Totp                 interface{} `json:"totp"`
	PasswordRevisionDate *string     `json:"passwordRevisionDate"`
	Uris                 []Uris      `json:"uris"`
}

type Uris struct {
	Match interface{} `json:"match"`
	URI   string      `json:"uri"`
}

type PasswordHistory struct {
	LastUsedDate string `json:"lastUsedDate"`
	Password     string `json:"password"`
}

type SecureNote struct {
	Type int64 `json:"type"`
}

type Object string

const (
	Item Object = "item"
)
